name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js 18.16.1
        uses: actions/setup-node@master
        with:
          node-version: 18.18.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.6

      # 生成静态文件
      - name: Build
        run: pnpm install && pnpm build:prod

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "dist"

      # 部署到服务器
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 公网 IP 或 域名
          username: ${{ secrets.USERNAME }} # 登录名
          password: ${{ secrets.PASSWORD }} # 密码
          port: ${{ secrets.PORT }} # 端口
          name: Deploy GitHub Pages

# 触发条件：在 push 到 master 分支后
on:
  push:
    branches:
      - master

# 任务
jobs:
  build-and-deploy:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js 18.16.1
        uses: actions/setup-node@master
        with:
          node-version: 18.18.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.6

      # 生成静态文件
      - name: Build
        run: pnpm install && pnpm build:prod

      # 部署到 GitHub Pages
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "dist"

      # 部署到服务器
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # 公网 IP 或 域名
          username: ${{ secrets.USERNAME }} # 登录名
          password: ${{ secrets.PASSWORD }} # 密码
          port: ${{ secrets.PORT }} # 端口
          FOLDER: "dist"
          remoteDir: "/data/web/gxjh" #前端部署地址: "dist" 